// Package annogo provides runtime support for Go annotations. This package is
// referenced from code generated by aptgo, for providing runtime accesss to
// annotation values that are intended to be runtime-visible.
//
// The various Register* functions should not be called directly, but instead
// only called from generated code. The other functions can then be used to
// inspect runtime-visible annotation values (which were registered from said
// generated code during package initialization).
//
// It also provides the foundational meta-annotations, which Go package authors
// use to define their own annotations.
package annogo
